const react = require("eslint-plugin-react");
const reactHooks = require("eslint-plugin-react-hooks");
const babelParser = require("@babel/eslint-parser");

module.exports = [
  {
    files: ["src/App.jsx"],
    languageOptions: {
      parser: babelParser,
      ecmaVersion: 2022,
      sourceType: "module",
      parserOptions: {
        requireConfigFile: false,
        babelOptions: {
          presets: ["@babel/preset-react"],
        },
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        navigator: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        Image: "readonly",
        Blob: "readonly",
        URL: "readonly",
        FileReader: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        AbortController: "readonly",
        process: "readonly",
        crypto: "readonly",
        Intl: "readonly",
        URLSearchParams: "readonly",
        atob: "readonly",
        btoa: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        Notification: "readonly",
        PublicKeyCredential: "readonly",
        RTCPeerConnection: "readonly",
        RTCSessionDescription: "readonly",
        RTCIceCandidate: "readonly",
        Audio: "readonly",
        WebSocket: "readonly",
        performance: "readonly",
        location: "readonly",
        history: "readonly",
        FormData: "readonly",
        File: "readonly",
        Worker: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        matchMedia: "readonly",
        requestIdleCallback: "readonly",
        cancelIdleCallback: "readonly",
        structuredClone: "readonly",
        Notification_: "readonly",
      },
    },
    plugins: {
      react,
      "react-hooks": reactHooks,
    },
    rules: {
      "no-undef": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-const-assign": "error",
      "no-redeclare": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-self-assign": "error",
      "no-unsafe-negation": "error",
      "no-case-declarations": "error",
      "react/jsx-no-undef": "error",
      "react/jsx-key": "warn",
      "react/no-direct-mutation-state": "error",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      "no-unused-vars": "off",
    },
  },
];
